name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration - Static Analysis", "Continuous Integration - Audit"]
    types: [completed]
    branches: [main]

concurrency:
  group: deployment
  cancel-in-progress: false

env:
  WASM_TARGET: wasm32-unknown-unknown
  TRUNK_OUTPUT_DIR: dist

jobs:
  deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success'
      && github.event.workflow_run.name == 'Continuous Integration - Static Analysis' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: ${{ env.WASM_TARGET }}

      - name: Install Brioche
        uses: brioche-dev/setup-brioche@v1.5.0

      - name: Install trunk
        run: brioche install -r trunk

      - name: Cache cargo registry + build
        uses: actions/cache@v5.0.1
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/git/db
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            target
          key: deployment-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: trunk build --release --public-url "/"

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ env.TRUNK_OUTPUT_DIR }} --project-name=${{ github.event.repository.name }} --branch=${{ github.ref_name }}
